"""提示词模板模块。"""

from src.prompts.prompts import (
    PROMPT_REFINEMENT_SYSTEM,
    PROMPT_REFINEMENT_USER_RESOLVE,
    PROMPT_REFINEMENT_USER_IMPROVE,
    PROMPT_SOLUTION_SYSTEM,
    PROMPT_SOLUTION_USER,
    PROMPT_VERIFICATION_SYSTEM,
    PROMPT_VERIFICATION_USER,
    PromptBuilder,
)

__all__ = [
    "PROMPT_SOLUTION_SYSTEM",
    "PROMPT_SOLUTION_USER",
    "PROMPT_VERIFICATION_SYSTEM",
    "PROMPT_VERIFICATION_USER",
    "PROMPT_REFINEMENT_SYSTEM",
    "PROMPT_REFINEMENT_USER_RESOLVE",
    "PROMPT_REFINEMENT_USER_IMPROVE",
    "PromptBuilder",
]

